def verifyThatSetupAndConfigurationPopupIsDisplayed():  
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  aqObject.CheckProperty(securitySetup, "WPFControlText", cmpEqual, "Security Setup")
  expander = securitySetup.expUsers
  aqObject.CheckProperty(expander, "WPFControlText", cmpEqual, "Users")
  aqObject.CheckProperty(securitySetup.TextblockSelectAUserGroupOrClickTheButton, "WPFControlText", cmpEqual, "Select a User/Group or click the + button.")
  
def clickOnAddUserButton():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  expander = securitySetup.expUsers
  expander.Click(261, 21)

def verifyThatUserInformationAndPermissionsSectionIsDisplayed():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  aqObject.CheckProperty(securitySetup.TextblockUserInformation, "WPFControlText", cmpEqual, "User Information")
  aqObject.CheckProperty(securitySetup.TextblockPermissions, "WPFControlText", cmpEqual, "Permissions")
  
def verifyThatUserIDIsAutoGenerated():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  aqObject.CheckProperty(securitySetup.TextboxUserId, "wText", cmpMatches, "\z")
  
def enterNonAdminUserDetails(userName, fullName, email, password, timeOutInActivity):
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  textBox = securitySetup.txtUserName
  textBox.SetText(userName)
  textBox2 = securitySetup.TextboxFullName
  textBox2.SetText(fullName)
  textBox3 = securitySetup.TextboxEmail
  textBox3.SetText(email)
  passwordBox = securitySetup.PasswordBox
  passwordBox.SetText(password)
  passwordBox2 = securitySetup.PasswordboxVerify
  passwordBox2.SetText(password)
  toggleButton = securitySetup.ToggleButton
  toggleButton.ClickButton(cbChecked)
  textBox4 = securitySetup.TextBox
  textBox4.SetText(timeOutInActivity)

def verifyThatUserDetailsAreEnteredCorrectly(userName, fullName, email, password, timeOutInActivity):
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  aqObject.CheckProperty(securitySetup.txtUserName, "wText", cmpEqual, userName)
  aqObject.CheckProperty(securitySetup.TextboxFullName, "wText", cmpEqual, fullName)
  aqObject.CheckProperty(securitySetup.TextboxEmail, "wText", cmpEqual, email)
  aqObject.CheckProperty(securitySetup.PasswordBox, "wText", cmpEqual, password)
  aqObject.CheckProperty(securitySetup.PasswordboxVerify, "wText", cmpEqual, password)
  aqObject.CheckProperty(securitySetup.ToggleButton, "wState", cmpEqual, 1)
  aqObject.CheckProperty(securitySetup.TextBox, "wText", cmpEqual, timeOutInActivity)
  
def selectCamerasAndItsPermissions():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  tabControl = securitySetup.TabControl
  xamDataGrid = tabControl.gridCameraPermissions
  xamDataGrid.ClickCell(3, "AllowViewing")
  xamDataGrid.ClickCell(3, "AllowPlayback")
  xamDataGrid.ClickCell(10, "AllowViewing")
  
def verifyThatCameraPermissionsAreSelectedCorrectly():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  xamDataGrid = securitySetup.TabControl.gridCameraPermissions
  recordListControl = xamDataGrid.RecordListControl
  aqObject.CheckProperty(recordListControl.XamCheckEditor, "IsChecked", cmpEqual, True)
  aqObject.CheckProperty(recordListControl.XamCheckEditor2, "IsChecked", cmpEqual, True)
  aqObject.CheckProperty(recordListControl.XamCheckEditor3, "IsChecked", cmpEqual, True)
  aqObject.CheckProperty(recordListControl.XamCheckEditor4, "IsChecked", cmpEqual, False)
  
def selectOtherResourcesPermissions():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  tabControl = securitySetup.TabControl
  tabControl.ClickTab("Other Resources")
  xamDataGrid = tabControl.gridResourcePermissions
  xamDataGrid.ClickCell(2, "HasPermission")
  xamDataGrid.ClickCell(3, "HasPermission")
  
def verifyThatOtherResourcesAreSelectedCorrectly():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  xamDataGrid = securitySetup.TabControl.gridResourcePermissions
  recordListControl = xamDataGrid.RecordListControl
  aqObject.CheckProperty(recordListControl.XamCheckEditor, "IsChecked", cmpEqual, True)
  aqObject.CheckProperty(recordListControl.XamCheckEditor2, "IsChecked", cmpEqual, True)
  
def clickSaveButtonOnUserCreationPopup():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  button = securitySetup.ButtonSave
  aqObject.CheckProperty(button, "Enabled", cmpEqual, True)
  button.ClickButton()
  aqObject.CheckProperty(button, "Enabled", cmpEqual, False)
  
def closeSecuritySetupPopup():
  securitySetup = Aliases.VIMonitorPlus.HwndSource_SecuritySetup.SecuritySetup
  securitySetup.WindowButtonCommands.Click(106, 19)
  
